-- UTC

-- ALTA PRECISION
SELECT SYSDATETIME() AS 'SYSDATETIME'; -- Horario del sistema
SELECT SYSDATETIMEOFFSET() AS 'SYSDATETIMEOFFSET';
SELECT  SYSUTCDATETIME() AS 'SYSUTCDATETIME';

--BAJA PRECISION
SELECT GETDATE() AS 'GETDATE';
SELECT CURRENT_TIMESTAMP AS 'CURRENT_TIMESTAMP';
--SELECT CURRENT_TRANSACTION_ID();
SELECT GETUTCDATE() AS 'GETUTCDATE';

--OBTENER SOLO EL PARTES DEL MES
-------------------------------------------------
--OBTENER SOLO EL AÑO DE UNA FECHA
SELECT DATEPART(YEAR,'2002-10-08'); --EJEMPLO #1
SELECT DATEPART(YEAR, GETDATE()); --EJEMPLO #2

--OBTTENER SOLO EL MES DE UNA FECHA